# Generated by Django 5.1.5 on 2025-02-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.tipoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('senha', models.CharField(max_length=128)),
                ('tipo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.tipouser')),
            ],
        ),
        migrations.CreateModel(
            name='Barraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('feira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.feira')),
                ('dono_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoBarraca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barraca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.barraca')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.produto')),
            ],
            options={
                'unique_together': {('produto', 'barraca')},
            },
        ),
    ]
