# Generated by Django 5.1.6 on 2025-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feira", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="barraca",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="barraca",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="barraca",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
