# Generated by Django 5.1.5 on 2025-02-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('total_usuarios', models.IntegerField()),
                ('termos_mais_pesquisados', models.TextField()),
                ('locais_mais_populares', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='barraca',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='nota_media',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='barraca',
            name='dono_user',
            field=models.ForeignKey(limit_choices_to={'tipo_user__descricao': 'Feirante'}, on_delete=django.db.models.deletion.CASCADE, to='feira.user'),
        ),
        migrations.AlterField(
            model_name='feira',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoproduto',
            name='descricao',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PesquisaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_pesquisa', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('barraca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feira.barraca')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feira.produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feira.user')),
            ],
        ),
    ]
